### ISSUE TITLE
UIActivityIndicator not shown

### ISSUE THREAD

**Issue by dlinsin** [gcamp/GCDiscreetNotificationView#2]
When switching showActivity from YES to NO and then back to YES, it doesn't display the UIActivityIndicator. My workaround is to have to instances of GCDiscreetNotificationView, however looking at the code I think it should be possible to switch from YES to NO and back?

**Comment by gcamp** [comment]
Just looked into this and the problem is more complicated then it seems.

In the first call, the GCDiscreetNotificationView hide itself to change the value in the background. In the second call, the notification view thinks it's hided so it changes the value directly, but then the callback of the animation is called and the first value is changed again. 

I don't think there's a way to change the context of an animation while it's in action... So I don't know how to fix this except with a complete rewrite. 

Any idea?

**Comment by dlinsin** [comment]
I agree, I guess it's not possible to change the context on a running animation. I think the bug has something to do with the method

``` objective-c
- (void) setShowActivity:(BOOL) activity
```

since 

``` objective-c
- (void) animationDidStop:(NSString *)animationID finished:(BOOL) finished context:(void *) context
```

in my case doesn't change the activity indicator, it only calls stop.

However, I'm afraid I'm not fully understanding your code in order to help you out.

**Comment by gcamp** [comment]
Just made some changes that should fix the problem. I'm not closing the issue because this type of bug is not easy to reproduce. Still, I think it's fixed.

**Comment by dlinsin** [comment]
Thanks, I'll pull the changes and check it out.

**Comment by dlinsin** [comment]
Unfortunately, it doesn't solve the issue...still the same behaviour

**Comment by gcamp** [comment]
Can you send me a snipet or the viewcontroller where you use the notification view? I'm not able to reproduce the issue…
You can sent it via DM if you want.

**Comment by dlinsin** [comment]
With your latest changes this works perfectly! Thanks a lot!
